[UKI]
Cmdline=@/etc/kernel/cmdline
SecureBootSigningTool=sbsign
SecureBootPrivateKey=/var/lib/sbctl/keys/db/db.key
SecureBootCertificate=/var/lib/sbctl/keys/db/db.pem
PCRBanks=sha256
PCRPKey=/etc/systemd/tpm2-pcr-public-key.pem


[PCRSignature:initrd]
Phases=enter-initrd
PCRPrivateKey=/etc/systemd/pcr_policy_initrd_private.key
PCRPublicKey=/etc/systemd/pcr_policy_initrd_public.key

[PCRSignature:system]
PCRPrivateKey=/etc/systemd/tpm2-pcr-private-key.pem
PCRPublicKey=/etc/systemd/tpm2-pcr-public-key.pem
Phases=enter-initrd,enter-initrd:leave-initrd,enter-initrd:leave-initrd:sysinit,enter-initrd:leave-initrd:sysinit:ready
